#**Importing, Reading and Inspecting the dataset**

In [ ]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
#STEP-2: Autheticate E-Mail ID
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
#STEP-3: Get File from Drive using file-ID
downloaded = drive.CreateFile({'id':'14YW92TeU4Q-EJNmU_p5KkOOSXkc2jtni'}) # replace the id with id of file you want to access
downloaded.GetContentFile('auto-mpg.xls')

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('auto-mpg.xls')
df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [ ]:
# Number of rows and columns 
df.shape

(398, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [ ]:
df.describe().T

count         mean         std     min       25%     50%  \
mpg           398.0    23.514573    7.815984     9.0    17.500    23.0   
cylinders     398.0     5.454774    1.701004     3.0     4.000     4.0   
displacement  398.0   193.425879  104.269838    68.0   104.250   148.5   
weight        398.0  2970.424623  846.841774  1613.0  2223.750  2803.5   
acceleration  398.0    15.568090    2.757689     8.0    13.825    15.5   
model year    398.0    76.010050    3.697627    70.0    73.000    76.0   
origin        398.0     1.572864    0.802055     1.0     1.000     1.0   

                   75%     max  
mpg             29.000    46.6  
cylinders        8.000     8.0  
displacement   262.000   455.0  
weight        3608.000  5140.0  
acceleration    17.175    24.8  
model year      79.000    82.0  
origin           2.000     3.0

In [ ]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

#a) Dropping the name and origin columns

In [ ]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [ ]:
df = pd.DataFrame(df)
df = df.drop(['origin', 'car name'], axis=1)
df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

# b) Filling up the 'horsepower' columns's null values with mean values of the column

In [ ]:
x = df["horsepower"][0]
type((x))

str

In [ ]:
df['horsepower']

0      130
1      165
2      150
3      150
4      140
      ... 
393     86
394     52
395     84
396     79
397     82
Name: horsepower, Length: 398, dtype: object

In [ ]:
l = []
num = []
for i in df['horsepower']:
  try:
    i = int(i)
    num.append(i)
  except:
    pass
df['horsepower'] = df['horsepower'].replace("?",np.mean(num))
df["horsepower"] = df["horsepower"].astype("int64")



In [ ]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0         130    3504          12.0   
1    15.0          8         350.0         165    3693          11.5   
2    18.0          8         318.0         150    3436          11.0   
3    16.0          8         304.0         150    3433          12.0   
4    17.0          8         302.0         140    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0          86    2790          15.6   
394  44.0          4          97.0          52    2130          24.6   
395  32.0          4         135.0          84    2295          11.6   
396  28.0          4         120.0          79    2625          18.6   
397  31.0          4         119.0          82    2720          19.4   

     model year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

# c) Replacing 2 digits with 4 digits

In [ ]:
l = []
for i in df['model year']:
  i = '19'+str(i)
  l.append(int(i))


df['model year'] = l
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0         130    3504          12.0   
1    15.0          8         350.0         165    3693          11.5   
2    18.0          8         318.0         150    3436          11.0   
3    16.0          8         304.0         150    3433          12.0   
4    17.0          8         302.0         140    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0          86    2790          15.6   
394  44.0          4          97.0          52    2130          24.6   
395  32.0          4         135.0          84    2295          11.6   
396  28.0          4         120.0          79    2625          18.6   
397  31.0          4         119.0          82    2720          19.4   

     model year  
0          1970  
1          1970  
2          1970  
3          1970  
4          1970  
..          ...  
393        1982  
394        1982  
395        1982  
396        1982  
397        1982  

[398 rows x 7 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    int64  
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
dtypes: float64(3), int64(4)
memory usage: 21.9 KB


# d) 50/50 splitting the dataset into training and validation set

In [ ]:
X = df.drop(["mpg"],axis=1).values
y = df["mpg"].values

In [ ]:
X

array([[   8. ,  307. ,  130. , 3504. ,   12. , 1970. ],
       [   8. ,  350. ,  165. , 3693. ,   11.5, 1970. ],
       [   8. ,  318. ,  150. , 3436. ,   11. , 1970. ],
       ...,
       [   4. ,  135. ,   84. , 2295. ,   11.6, 1982. ],
       [   4. ,  120. ,   79. , 2625. ,   18.6, 1982. ],
       [   4. ,  119. ,   82. , 2720. ,   19.4, 1982. ]])

In [ ]:
X.shape

(398, 6)

In [ ]:
y

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [ ]:
y.shape

(398,)

In [ ]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
X = st.fit_transform(X)
# y = np.array(y)
# y = st.fit_transform(y.reshape(-1, 1))

In [ ]:
X


array([[ 1.49819126,  1.0906037 ,  0.66938081,  0.63086987, -1.29549834,
        -1.62742629],
       [ 1.49819126,  1.5035143 ,  1.58678287,  0.85433297, -1.47703779,
        -1.62742629],
       [ 1.49819126,  1.19623199,  1.19361056,  0.55047045, -1.65857724,
        -1.62742629],
       ...,
       [-0.85632057, -0.56103873, -0.53634763, -0.79858454, -1.4407299 ,
         1.62198339],
       [-0.85632057, -0.70507731, -0.66740507, -0.40841088,  1.10082237,
         1.62198339],
       [-0.85632057, -0.71467988, -0.5887706 , -0.29608816,  1.39128549,
         1.62198339]])

In [ ]:
X.shape

(398, 6)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.50, random_state = 40)

In [ ]:
a = len(X_train) + len(y_train) 
b = len(X_test) + len(y_test)
print('Training set length: {} | Testing set length: {}'.format(a,b))
print('X Training set length:',len(X_train))
print('Y Training set length:',len(y_train))
print('X Testing set length:',len(X_test))
print('Y Testing set length:',len(y_test))

Training set length: 398 | Testing set length: 398
X Training set length: 199
Y Training set length: 199
X Testing set length: 199
Y Testing set length: 199


In [ ]:
X_train

array([[-1.44494853, -1.18520592, -0.3790787 , -1.00076544, -0.75088   ,
        -0.81507387],
       [ 1.49819126,  1.98364292,  2.24207007,  1.71626206, -1.1139589 ,
        -1.08585801],
       [-0.85632057, -0.69547474,  0.14515105, -0.36702882, -0.56934055,
        -0.81507387],
       ...,
       [ 1.49819126,  2.36774581,  2.89735726,  1.58620417, -2.56627448,
        -1.62742629],
       [-0.85632057, -0.68587217, -0.22180977, -0.79267282, -0.02472221,
         0.26806269],
       [-0.85632057, -0.99315448, -1.47996118, -0.75129076,  2.95252475,
         1.08041511]])

In [ ]:
X_train.shape

(199, 6)

In [ ]:
y_train

array([18. , 13. , 24. , 21. , 13. , 34.4, 29.8, 15. , 19. , 26. , 20.2,
       22. , 37.3, 27.9, 23.8, 30.7, 13. , 14. , 22. , 19. , 27. , 35.1,
       15. , 24. , 19. , 16. , 28. , 23. , 35. , 26. , 18. , 26. , 17. ,
       29.5, 26. , 14. , 21.5, 18. , 13. , 46.6, 21. , 43.1, 36. , 19. ,
       15. , 34.2, 30.9, 24.5, 15. , 13. , 14. , 25.8, 21. , 27.5, 31. ,
       14. , 25. , 25. , 25. , 21. , 26.6, 37. , 28. , 15. , 14. , 27.4,
       17. , 11. , 19. , 15. , 34. , 23. , 17.7, 32. , 10. , 21.5, 20. ,
       21.5, 26. , 23.5, 41.5, 16. , 13. , 18.6, 20.2, 24.2, 23.2, 13. ,
       15.5, 32.4, 23. , 18. , 22. , 39.4, 16. , 30. , 24.5, 21. , 32. ,
       18. , 18. , 11. , 24. , 21. , 15.5, 34.7, 21.6, 27. , 25. , 39. ,
       13. , 16.2, 19.9, 20.2, 15. , 20. , 19.4, 18.5, 36. , 36. , 32. ,
       27. , 13. , 28. , 25. , 26.5, 36.1, 36. , 16. , 23.6, 15. , 15. ,
       29. , 14. , 25.5, 19. , 28. , 32.4, 24. , 31. , 16. , 27. , 16.5,
       18. , 22. , 29. , 30. , 31.5, 26. , 12. , 18

In [ ]:
y_train.shape

(199,)

# e) Training the keras sequential model

In [ ]:
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.activations import relu, softmax
from tensorflow.keras.losses import BinaryCrossentropy, MeanSquaredError
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam, RMSprop
import tensorflow as tf

In [ ]:
model = tf.keras.Sequential([
    Dense(units = 30, activation = relu, input_shape = [X_train.shape[1]]),
    Dense(units = 20, activation = relu),
    Dense(units = 1)
    ])

In [ ]:
model.summary()

Model: "sequential_20"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_60 (Dense)            (None, 30)                210       
                                                                 
 dense_61 (Dense)            (None, 20)                620       
                                                                 
 dense_62 (Dense)            (None, 1)                 21        
                                                                 
Total params: 851
Trainable params: 851
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss = 'mse', optimizer = RMSprop(0.001), metrics = ['mae','mse'])

In [ ]:
history = model.fit(X_train, y_train, epochs = 100,validation_data=(X_test, y_test))

Epoch 1/100
7/7 [==============================] - 1s 36ms/step - loss: 598.3011 - mae: 23.1011 - mse: 598.3011 - val_loss: 562.2723 - val_mae: 22.3388 - val_mse: 562.2723
Epoch 2/100
7/7 [==============================] - 0s 8ms/step - loss: 581.3430 - mae: 22.7209 - mse: 581.3430 - val_loss: 547.5125 - val_mae: 21.9828 - val_mse: 547.5125
Epoch 3/100
7/7 [==============================] - 0s 7ms/step - loss: 566.0638 - mae: 22.3626 - mse: 566.0638 - val_loss: 529.8566 - val_mae: 21.5671 - val_mse: 529.8566
Epoch 4/100
7/7 [==============================] - 0s 7ms/step - loss: 548.2863 - mae: 21.9531 - mse: 548.2863 - val_loss: 510.8956 - val_mae: 21.1203 - val_mse: 510.8956
Epoch 5/100
7/7 [==============================] - 0s 7ms/step - loss: 529.4192 - mae: 21.5154 - mse: 529.4192 - val_loss: 491.5301 - val_mae: 20.6527 - val_mse: 491.5301
Epoch 6/100
7/7 [==============================] - 0s 9ms/step - loss: 510.1918 - mae: 21.0635 - mse: 510.1918 - val_loss: 471.4330 - val_mae: 2

In [ ]:
y_pred = model.predict(X_test)

7/7 [==============================] - 0s 2ms/step


In [ ]:
pd.DataFrame(list(zip(y_test,y_pred)), columns = ['Actual Values', 'Predicted Values'])

Actual Values Predicted Values
0             26.0      [30.302855]
1             18.0      [14.209573]
2             22.0       [22.64322]
3             32.8       [35.36071]
4             24.0      [25.982405]
..             ...              ...
194           20.0      [17.897125]
195           37.2      [35.831127]
196           18.0      [22.218996]
197           14.0     [14.3778925]
198           44.3       [37.64377]

[199 rows x 2 columns]

In [ ]:
from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

0.8554930833886697

In [ ]:
X_test

array([[-0.85632057, -1.09878277, -0.98194292, -1.19112289, -0.02472221,
        -0.54428973],
       [ 0.32093534,  0.30319277,  0.01409361,  0.75974542,  0.33835669,
        -0.54428973],
       [-0.85632057, -0.69547474, -0.74603953, -0.54319814,  0.88297504,
        -1.08585801],
       ...,
       [ 0.32093534,  0.54325708, -0.69361655,  0.71363398,  1.97221172,
        -0.00272145],
       [ 1.49819126,  1.19623199,  1.19361056,  1.33081778, -0.93241945,
        -1.35664215],
       [-0.85632057, -0.99315448, -1.47996118, -1.04687687,  2.22636695,
         1.08041511]])

#f) Query & Prediction

In [ ]:
# initializing the data
data = [[6,2170,502,3164,4.2,2022], 
        [12,6498,730,3472,3.2,2022], 
        [8,3902,986,3020,2.5,2022], 
        [8,6162,670,3721,2.6,2022], 
        [4,122,181,2496,8.3,2022], 
        [6,3232,155,3232,11.5,1969], 
        [3,598,89,1550,10.1,2022], 
        [3,900,50,642,5.8,2022], 
        [4,1189,60,2355,28.1,1964], 
        [4,201,40,2265,32,1908], 
        ]
  
newDF = pd.DataFrame(data, columns=['Cylinder', 'Displacement','Horse Power', 'Weight','Acceleration', 'Year'])
  
# print dataframe.
newDF

Cylinder  Displacement  Horse Power  Weight  Acceleration  Year
0         6          2170          502    3164           4.2  2022
1        12          6498          730    3472           3.2  2022
2         8          3902          986    3020           2.5  2022
3         8          6162          670    3721           2.6  2022
4         4           122          181    2496           8.3  2022
5         6          3232          155    3232          11.5  1969
6         3           598           89    1550          10.1  2022
7         3           900           50     642           5.8  2022
8         4          1189           60    2355          28.1  1964
9         4           201           40    2265          32.0  1908

In [ ]:
model.predict(newDF)

1/1 [==============================] - 0s 49ms/step


array([[12741.342],
       [20010.14 ],
       [12367.532],
       [19445.826],
       [14401.333],
       [13483.919],
       [12343.692],
       [12513.233],
       [12128.254],
       [13482.612]], dtype=float32)